name: Build OpenWrt X86_64

on:

  push:

    branches:

      - main

  workflow_dispatch:

env:

  TZ: Asia/Shanghai

jobs:

  build:

    name: Build

    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@v2

        with:

          submodules: true

      - name: Update feeds

        run: |

          cd ${{ env.GITHUB_WORKSPACE }}/feeds

          git pull -q

          cd ${{ env.GITHUB_WORKSPACE }}

          ./scripts/feeds update -a

      - name: Install feeds

        run: |

          ./scripts/feeds install -a

      - name: Install dependencies

        run: |

          sudo apt-get update

          sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev libssl-dev libelf-dev git

      - name: Compile

        run: |

          date=`date '+%Y-%m-%d_%H-%M-%S'`

          make -j$(nproc) V=s | tee build_$date.log

      - name: Upload build artifacts

        uses: actions/upload-artifact@v2

        with:

          name: OpenWrt X86_64 Build Artifacts

          path: |

            ${{ env.GITHUB_WORKSPACE }}/bin/targets/x86/64/*.gz

            ${{ env.GITHUB_WORKSPACE }}/bin/targets/x86/64/*.zip

            ${{ env.GITHUB_WORKSPACE }}/build_*.log

